# Generated by Django 2.0.1 on 2018-01-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('event_time', models.CharField(max_length=500)),
                ('event_owner', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=10000)),
            ],
        ),
    ]
