# Generated by Django 2.0.2 on 2018-02-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
