# Generated by Django 2.0.2 on 2018-02-04 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0005_auto_20180203_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_guest',
            field=models.ManyToManyField(related_name='guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_vendor',
            field=models.ManyToManyField(related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateField(null=True),
        ),
    ]
