# Generated by Django 2.0.2 on 2018-02-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20180205_0126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='TextAnswer',
        ),
        migrations.RenameField(
            model_name='textanswer',
            old_name='textquestion',
            new_name='question',
        ),
    ]
