# Generated by Django 2.0.2 on 2018-02-05 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0008_auto_20180205_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanswer',
            name='answeruser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answeruser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='permit_vendor',
            field=models.ManyToManyField(related_name='permit_vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
