# Generated by Django 2.0.2 on 2018-02-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20180205_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textquestion',
            name='question',
            field=models.TextField(max_length=200),
        ),
    ]
