# Generated by Django 2.0.2 on 2018-02-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20180205_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textquestion',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
