# Generated by Django 2.0.2 on 2018-02-06 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0014_auto_20180205_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_invitation',
            field=models.ManyToManyField(related_name='invitation', to=settings.AUTH_USER_MODEL),
        ),
    ]
