# Generated by Django 2.0.2 on 2018-02-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_event_event_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='textquestion',
            name='guest_canmodify',
            field=models.BooleanField(default=True),
        ),
    ]
