# Generated by Django 2.0.2 on 2018-02-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_textquestion_guest_canmodify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='event',
        ),
        migrations.AddField(
            model_name='textquestion',
            name='has_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='multi_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.TextQuestion'),
        ),
    ]
