# Generated by Django 2.0.2 on 2018-02-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20180207_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='textquestion',
            name='is_text',
            field=models.BooleanField(default=True),
        ),
    ]
