# Generated by Django 2.0.2 on 2018-02-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20180207_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multianswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='multianswer',
            name='user_answermulti',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='multianswer',
        ),
        migrations.DeleteModel(
            name='MultiAnswer',
        ),
    ]
