# Generated by Django 2.0.2 on 2018-02-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_multianswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='multianswer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multianswer', to='event.MultiAnswer'),
        ),
    ]
