# Generated by Django 2.0.2 on 2018-02-07 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0024_auto_20180207_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='multianswer',
            name='answer_muti_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_muti_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
