# Generated by Django 2.0.2 on 2018-02-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_multianswer_answer_muti_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='textquestion',
            name='permit_choice_number',
            field=models.IntegerField(default=1),
        ),
    ]
