# Generated by Django 2.0.2 on 2018-02-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_textquestion_permit_choice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='permit_plus_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='plus_one',
            field=models.BooleanField(default=False),
        ),
    ]
