# Generated by Django 2.0.2 on 2018-02-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_auto_20180209_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='plus_one',
            new_name='support_plus_one',
        ),
    ]
